### ISSUE TITLE
Amazing work !!!  Just - got blocked when needing to do the frontend part : S

### ISSUE THREAD

**Issue by kikomayorga** [pamelus/lua-captive-portal#9]
Dear Pamelus,

I have spent some two or three days testing and deciding how to move forward with the research i am doing for my thesis. The thesis is about how to modulate the access to the internet so that children won´t stick for so long in front of screens. I have loved your "on screen token concept" so i started following your installation instructions a few times. The problem that i am having is always that i cannot compile node-npm for my TP Link Archer C5 AC1200 : S   /// So i´ve tried to see if your earlier versions maybe did come with something simpler for the front end ....  I hope to be able to chat with you! Maybe i can hire you (?) to do some mods for me ? : O around your fantastic solution !  Please let me know at kikomayorga@gmail.com if you feel like chatting about this possibility !  Best, KIko

**Comment by ptkoz** [comment]
Hey @kikomayorga you don't really need node-npm on your device. You should instead build the frontend bundle on your local computer and then upload output files to the router. Frontend on its own is totally static and doesn't need any software on router (other that a http server, like uhttpd).

**Comment by kikomayorga** [comment]
Ok, Pamelus! Thanks for the tip <3  I will try that today and let you know!  Still, i´d like to meet you and see if we can collaborate : )  Best and thanks again!

**Comment by kikomayorga** [comment]
Hello @pamelus ! This time it seems i moved a bit further. As i can see the screenshot below:
![screenshot_pamelus](https://user-images.githubusercontent.com/1235956/181852776-f1fc5d0a-b2ba-4e9c-9b6a-0e56e8b5dc9a.png)

But still, i think i did something wrong while building the frontend using yarn and node, because even if i got the files at the folder public_html i also got some errors saying the lines below... 

Probably i will take a rest and see if specific node versions work better : ) 

Thanks! 

enrique@ZENUBUNTU:~/captive-frontend/captive-frontend$ TOKEN_API="http://192.168.1.1:6820/captive.lua/auth.token" yarn build
yarn run v1.22.19
$ webpack --config webpack.production.config.js
Hash: 259207066e68f4ada2ec
Version: webpack 4.46.0
Time: 50855ms
Built at: 07/29/2022 4:02:51 PM
 1 asset
Entrypoint main = index.js

ERROR in /home/enrique/captive-frontend/captive-frontend/src/Components/form/SignInForm.tsx
[tsl] ERROR in /home/enrique/captive-frontend/captive-frontend/src/Components/form/SignInForm.tsx(46,40)
  	TS2345: Argument of type 'ConnectedComponent<typeof SignInForm, Pick<ClassAttributes<SignInForm> & ISignInFormProps, "ref" | "key">>' is not assignable to parameter of type 'ComponentClass<RouteComponentProps<any, StaticContext, unknown>, any> | FunctionComponent<RouteComponentProps<any, StaticContext, unknown>> | (FunctionComponent<...> & ComponentClass<...>) | (ComponentClass<...> & FunctionComponent<...>)'.
  Type 'ConnectedComponent<typeof SignInForm, Pick<ClassAttributes<SignInForm> & ISignInFormProps, "ref" | "key">>' is not assignable to type 'FunctionComponent<RouteComponentProps<any, StaticContext, unknown>>'.
	Types of parameters 'props' and 'props' are incompatible.
  	Type 'PropsWithChildren<RouteComponentProps<any, StaticContext, unknown>>' has no properties in common with type 'Pick<ClassAttributes<SignInForm> & ISignInFormProps, "ref" | "key">'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
enrique@ZENUBUNTU:~/captive-frontend/captive-frontend$

**Comment by kikomayorga** [comment]
Fantastic!!! It Works!!! 
![yay](https://user-images.githubusercontent.com/1235956/181875805-e0922987-5bd8-4d81-b0cb-fcfb00f53490.png)
